version: "3"

services:
  auto-tests:
    container_name: pw-tests
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./playwright-report:/pw-tests/playwright-report
    environment:
      CI: true
      BASE_URL: $BASE_URL
      HTTP_CREDENTIALS_USERNAME: $HTTP_CREDENTIALS_USERNAME
      HTTP_CREDENTIALS_PASSWORD: $HTTP_CREDENTIALS_PASSWORD
#
#  db:
#    image: mysql
#    restart: always
#    environment:
#      MYSQL_ROOT_PASSWORD: example
