name: "Automated tests with Playwright"

on:
  - pull_request
  - push
  - workflow_dispatch

jobs:
  playwright-tests:
    runs-on: ubuntu-22.04
    container: mcr.microsoft.com/playwright:v1.56.1-jammy
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4
      - name: "Install node js"
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: "Install dependecies"
        run: npm ci
      - name: "run tests"
        run: npm test
        env:
          BASE_URL: ${{secrets.BASE_URL}}
          HTTP_CREDENTIALS_USERNAME: ${{secrets.HTTP_CREDENTIALS_USERNAME}}
          HTTP_CREDENTIALS_PASSWORD: ${{secrets.HTTP_CREDENTIALS_PASSWORD}}
      - name: "Upload tests report to artifacts"
        uses: actions/upload-artifact@v4
        with:
          name: report
          path: playwright-report/
          retention-days: 3
